routes/web.php
<?php

use App\User;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::group(['middleware' => 'auth'], function () {

	Route::get('/', 'HomeController@index')->name('home');;

    Route::resource('contatos', 'ContatoController');
    Route::get('/contatos/telefones/{telefone}', 'ContatoController@administraTelefones')->name('contatos.telefones');

    Route::resource('telefones', 'TelefoneController');
});

app/Contato.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Contato extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'facebook_link', 'linkedin_link'
    ];

    // hasMany relations
    public function telefones()
    {
        return $this->hasMany('App\Telefone');
    }

}

app/Telefone.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Telefone extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'numero', 'contato_id'
    ];

    // belongsTo relations
    public function contato()
    {
        return $this->belongsTo('App\Contato');
    }
}

app/User.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use Notifiable, HasRoles, SoftDeletes;

    //protected $connection = 'mysql_shared';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

}

app/Http/Controllers/ContatoController.php
<?php

namespace App\Http\Controllers;

use App\Contato;
use App\Services\ContatoService;
use Illuminate\Http\Request;

class ContatoController extends Controller
{
    /**
     * Servico de Contatos
     * @var \App\Services\ContatoService
     */
    protected $contatoService;

    /**
     * Create a new command instance.
     *
     * @return void
     */
    public function __construct(ContatoService $contatoService)
    {
        $this->contatoService = $contatoService;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $result = $this->contatoService->getAllContacts();

        return view('contatos.index', compact('result'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $contato = $this->contatoService->newContact();

        return view('contatos.new')->with(compact('contato'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request) 
    {
        // Adiciona novo contato
        if ($contato = $this->contatoService->storeContact($request->toArray())) {

            $this->contatoService->sendWelcomeEmail($contato->id);

            flash('Contato criado com sucesso.');

        } else {

            flash()->error('Não foi possível criar o contato. Contate o administrador.');

        }

        return redirect()->route('contatos.index');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(int $id)
    {
        $contato = $this->contatoService->findOrFailContact($id);

        return view('contatos.edit', compact('contato'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, int $id)
    {
        if ($this->contatoService->updateContact($request->toArray(), $id)) {
            flash()->success('Contato editado com sucesso.');
        } else {
            flash()->error('Não foi possível editar o contato.');
        }

        return redirect()->route('contatos.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     * @internal param Request $request
     */
    public function destroy(int $id)
    {
        if ($this->contatoService->destroyContact($id)) {
            flash()->success('Contato deletado com sucesso');
        } else {
            flash()->success('Não foi possível deletar o contato.');
        }

        return redirect()->route('contatos.index');
    }

    /**
     * Método administra os telefones do contato
     *
     * @param  int     $id  O identificador
     *
     * @return <type>  ( description_of_the_return_value )
     */
    public function administraTelefones(int $id)
    {
        $contato = $this->contatoService->findOrFailContact($id);

        return view('contatos.telefones', compact('contato'));
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Support\Facades\Route;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('pages.home');
    }

}

app/Http/Controllers/TelefoneController.php
<?php

namespace App\Http\Controllers;

use App\Services\TelefoneService;
use Illuminate\Http\Request;

class TelefoneController extends Controller
{
    /**
     * Servico de Telefones
     * @var \App\Services\TelefoneService
     */
    protected $telefoneService;

    /**
     * Create a new command instance.
     *
     * @return void
     */
    public function __construct(TelefoneService $telefoneService)
    {
        $this->telefoneService = $telefoneService;
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request) 
    {
        // Adiciona novo contato
        if ($telefone = $this->telefoneService->storeTelefone($request->toArray())) {

            flash('Telefone criado com sucesso.');

        } else {

            flash()->error('Não foi possível criar o telefone. Contate o administrador.');

        }

        return redirect()->route('contatos.telefones', $telefone->contato->id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     * @internal param Request $request
     */
    public function destroy(int $id)
    {
        if ($this->telefoneService->destroyTelefone($id)) {
            flash()->success('Telefone deletado com sucesso');
        } else {
            flash()->success('Não foi possível deletar o telefone.');
        }

        return redirect()->back();
    }
}

resources/views/contatos/_form.blade.php
            <div class="form-body">
                <div class="alert alert-danger display-hide">
                <button class="close" data-close="alert"></button>
                Você tem alguns erros de formulário. Por favor, verifique abaixo.
                </div>
                <div class="alert alert-success display-hide">
                <button class="close" data-close="alert"></button> Sua validação de formulário foi bem sucedida! </div>
                    <div class="form-group">
                        <label class="col-md-3 control-label">Nome
                        <span class="required"> * </span></label>
                        <div class="col-md-5">
                            <div class="input-icon right">
                                <i class="fa fa-user"></i>
                                <input name="name" type="text" class="form-control" placeholder="Enter name" value="{{ old('name') ? old('name') : $contato->name }}"> </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-3 control-label">Email
                        <span class="required"> * </span></label>
                        <div class="col-md-5">
                            <div class="input-icon right">
                                <i class="fa fa-envelope"></i>
                                <input name="email" type="text" class="form-control" placeholder="Email Address" value="{{ old('email') ? old('email') : $contato->email }}"> </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-3 control-label">Facebook
                        </label>
                        <div class="col-md-5">
                            <div class="input-icon right">
                                <i class="fa fa-facebook"></i>
                                <input name="facebook_link" type="text" class="form-control" placeholder="Enter facebook link" value="{{ old('name') ? old('name') : $contato->facebook_link }}"> </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-3 control-label">LinkedIn
                        </label>
                        <div class="col-md-5">
                            <div class="input-icon right">
                                <i class="fa fa-linkedin"></i>
                                <input name="linkedin_link" type="text" class="form-control" placeholder="Enter LinkedIn link" value="{{ old('name') ? old('name') : $contato->linkedin_link }}"> </div>
                        </div>
                    </div>
            </div>
            <div class="form-actions">
                <div class="row">
                    <div class="col-md-offset-3 col-md-9">
                        <button type="submit" class="btn blue-sharp">Salvar</button>
                        <a class="btn default" href="{{ route('contatos.index') }}">Cancelar</a>
                    </div>
                </div>
            </div>

resources/views/contatos/edit.blade.php
@extends('layouts.default')

@section('css-plugins')
        {{-- Select --}}
        <link href="{{ asset("assets/global/plugins/select2/css/select2.min.css") }}" rel="stylesheet" type="text/css" />
        <link href="{{ asset("assets/global/plugins/select2/css/select2-bootstrap.min.css") }}" rel="stylesheet" type="text/css" />

        {{-- File Input --}}
        <link href="{{ asset("assets/global/plugins/bootstrap-fileinput/bootstrap-fileinput.css") }}" rel="stylesheet" type="text/css" />
@endsection

@section('breadcumb')
	<li>
        <a href="{{ route('contatos.index') }}" class="nav-link nav-toggle">
            <span class="title">Contatos</span>
        </a>
        <i class="fa fa-circle"></i>
    </li>
    <li>
        Editar
    </li>
@endsection

@section('content')
	
    <h1 class="page-title">
    	Contatos
        <small>Editar</small>
    </h1>

        <div class="portlet light bordered">
            <div class="portlet-title">
                <div class="caption">
                    <i class="icon-equalizer font-blue-sharp"></i>
                    <span class="caption-subject font-blue-sharp bold uppercase">Editar Contato</span>
                    <span class="caption-helper">formulário para edição de contato</span>
                </div>
                <div class="actions">
                    
                </div>
            </div>
            <div class="portlet-body form">
                <!-- BEGIN FORM-->
                <form action="{{ route('contatos.update', $contato->id) }}" METHOD="POST" id="formUser" class="form-horizontal">
                    {{ csrf_field() }}
                    {{ method_field('PUT') }}
                    @include('contatos._form')
                </form>
                <!-- END FORM-->
            </div>
        </div>

    
@endsection

@section('before-plugins')
        {{-- Select --}}
        <script src="{{ asset("assets/global/plugins/select2/js/select2.full.min.js") }}" type="text/javascript"></script>

        {{-- Input File --}}
        <script src="{{ asset("assets/global/plugins/bootstrap-fileinput/bootstrap-fileinput.js") }}" type="text/javascript"></script>

        {{-- Mask --}}
        <script src="{{ asset("assets/global/plugins/jquery-inputmask/jquery.inputmask.bundle.min.js") }}" type="text/javascript"></script>
        <script src="{{ asset("assets/global/plugins/jquery.input-ip-address-control-1.0.min.js") }}" type="text/javascript"></script>

        {{-- Validation --}}
        <script src="{{ asset("assets/global/plugins/jquery-validation/js/jquery.validate.js") }}" type="text/javascript"></script>
        <script src="{{ asset("assets/global/plugins/jquery-validation/js/additional-methods.js") }}" type="text/javascript"></script>
@endsection

@section('after-plugins')
        {{-- Select --}}
        <script src="{{ asset("assets/pages/scripts/components-select2.min.js") }}" type="text/javascript"></script>

        {{-- Mask --}}
        <script src="{{ asset("assets/pages/scripts/form-input-mask.min.js") }}" type="text/javascript"></script>

        {{-- Validation --}}
        <script src="{{ asset("assets/pages/scripts/form-validation.js") }}" type="text/javascript"></script>
@endsection

@section('script')

@endsection

resources/views/contatos/index.blade.php
@extends('layouts.default')

@section('css-plugins')
        <!--Datatable-->
        <link href="{{ asset("assets/global/plugins/datatables/datatables.min.css") }}" rel="stylesheet" type="text/css" />
        <link href="{{ asset("assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.css") }}" rel="stylesheet" type="text/css" />
        <link href="{{ asset("assets/global/plugins/bootstrap-datepicker/css/bootstrap-datepicker3.min.css") }}" rel="stylesheet" type="text/css" />
@endsection

@section('breadcumb')
	<li>
            Contatos
	</li>
@endsection

@section('content')
	
    <h1 class="page-title">
    	Contatos
        <small>Index</small>
    </h1>


		<a class="btn blue-sharp btn-outline sbold pull-right" href="{{ route('contatos.create') }}"><i class="fa fa-user-plus"></i> Novo Contato</a>
		<div style="margin:0; padding:0; height:50px;">&nbsp;</div>

    <div class="row">
                <div class="col-md-12">
                                <!-- BEGIN EXAMPLE TABLE PORTLET-->
                                <div class="portlet light bordered">
                                    <div class="portlet-title">
                                        <div class="caption font-dark">
                                            <i class="icon-settings font-dark"></i>
                                            <span class="caption-subject bold uppercase">Contatos</b></span>
                                        </div>
                                        <div class="tools"> </div>
                                    </div>
                                    <div class="portlet-body">
                                        <table class="table table-striped table-bordered table-hover" id="sample_1">
                                            <thead>
                                                <tr>
                                                    <th>Nome</th>
                                                    <th>Email</th>
                                                    <th>Facebook</th>
                                                    <th>LinkedIn</th>
                                                    <th>Ações</th>
                                                </tr>
                                            </thead>
                                        <tbody>
                                            @foreach($result as $r)
                                                <tr>
                                                    <td>{{$r->name}}</td>
                                                    <td>{{$r->email}}</td>
                                                    <td>{{$r->facebook_link}}</td>
                                                    <td>{{$r->linkedin_link}}</td>
                                                    <td>
                                                        <div class="btn-group">
                                                            <button class="btn btn-xs blue-sharp dropdown-toggle" type="button" data-toggle="dropdown" aria-expanded="false"> Ações
                                                                <i class="fa fa-angle-down"></i>
                                                            </button>
                                                            <ul class="dropdown-menu pull-left" role="menu">
                                                                <li>
                                                                    <a href="{{ route('contatos.edit', $r->id) }}">
                                                                        <i class="fa fa-edit"></i> Editar </a>
                                                                </li>
                                                                <li>
                                                                    <a href="{{ route('contatos.telefones', $r->id) }}">
                                                                        <i class="fa fa-phone"></i> Telefones </a>
                                                                </li>
                                                                <li>
                                                                <form role="form" action="{{ route('contatos.destroy', $r->id) }}" METHOD="POST">
                                                                    {{ csrf_field() }}
                                                                    {{ method_field('DELETE') }}<button type="submit">Deletar</button>
                                                                </form>
                                                                </li>
                                                            </ul>
                                                        </div>
                                                    </td>
                                                </tr>
                                            @endforeach
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                                <!-- END EXAMPLE TABLE PORTLET-->
                </div>
    </div>
    
@endsection

@section('before-plugins')
        <!--Datatable-->
        <script src="{{ asset("assets/global/scripts/datatable.js") }}" type="text/javascript"></script>
        <script src="{{ asset("assets/global/plugins/datatables/datatables.min.js") }}" type="text/javascript"></script>
        <script src="{{ asset("assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.js") }}" type="text/javascript"></script>
        <script src="{{ asset("assets/global/plugins/bootstrap-datepicker/js/bootstrap-datepicker.min.js") }}" type="text/javascript"></script>
@endsection

@section('after-plugins')
        <!--Datatable-->
        <script src="{{ asset("assets/pages/scripts/table-datatables-buttons.min.js") }}" type="text/javascript"></script>

@endsection

@section('scripts')
 
@endsection

resources/views/contatos/new.blade.php
@extends('layouts.default')

@section('css-plugins')
        {{-- Select --}}
        <link href="{{ asset("assets/global/plugins/select2/css/select2.min.css") }}" rel="stylesheet" type="text/css" />
        <link href="{{ asset("assets/global/plugins/select2/css/select2-bootstrap.min.css") }}" rel="stylesheet" type="text/css" />

        {{-- File Input --}}
        <link href="{{ asset("assets/global/plugins/bootstrap-fileinput/bootstrap-fileinput.css") }}" rel="stylesheet" type="text/css" />
@endsection

@section('breadcumb')
	<li>
        <a href="{{ route('contatos.index') }}" class="nav-link nav-toggle">
            <span class="title">Contatos</span>
        </a>
        <i class="fa fa-circle"></i>
    </li>
    <li>
        Criar
    </li>
@endsection

@section('content')
	
    <h1 class="page-title">
    	Contatos
        <small>Criar</small>
    </h1>

        <div class="portlet light bordered">
            <div class="portlet-title">
                <div class="caption">
                    <i class="icon-equalizer font-blue-sharp"></i>
                    <span class="caption-subject font-blue-sharp bold uppercase">Criar novo Contato</span>
                    <span class="caption-helper">formulário para criação de novo contato</span>
                </div>
                <div class="actions">
                    
                </div>
            </div>
            <div class="portlet-body form">
                <!-- BEGIN FORM-->
                <form action="{{ route('contatos.store') }}" METHOD="POST" id="formUser" class="form-horizontal">
                {{ csrf_field() }}
                    @include('contatos._form')
                </form>
                <!-- END FORM-->
            </div>
        </div>

    
@endsection

@section('before-plugins')
        {{-- Select --}}
        <script src="{{ asset("assets/global/plugins/select2/js/select2.full.min.js") }}" type="text/javascript"></script>

        {{-- Input File --}}
        <script src="{{ asset("assets/global/plugins/bootstrap-fileinput/bootstrap-fileinput.js") }}" type="text/javascript"></script>

        {{-- Mask --}}
        <script src="{{ asset("assets/global/plugins/jquery-inputmask/jquery.inputmask.bundle.min.js") }}" type="text/javascript"></script>
        <script src="{{ asset("assets/global/plugins/jquery.input-ip-address-control-1.0.min.js") }}" type="text/javascript"></script>

        {{-- Validation --}}
        <script src="{{ asset("assets/global/plugins/jquery-validation/js/jquery.validate.js") }}" type="text/javascript"></script>
        <script src="{{ asset("assets/global/plugins/jquery-validation/js/additional-methods.js") }}" type="text/javascript"></script>
@endsection

@section('after-plugins')
        {{-- Select --}}
        <script src="{{ asset("assets/pages/scripts/components-select2.min.js") }}" type="text/javascript"></script>

        {{-- Mask --}}
        <script src="{{ asset("assets/pages/scripts/form-input-mask.min.js") }}" type="text/javascript"></script>

        {{-- Validation --}}
        <script src="{{ asset("assets/pages/scripts/form-validation.js") }}" type="text/javascript"></script>
@endsection

@section('script')
    <script type="text/javascript">
        
    </script>
@endsection

resources/views/contatos/telefones.blade.php
@extends('layouts.default')

@section('css-plugins')
        {{-- Select --}}
        <link href="{{ asset("assets/global/plugins/select2/css/select2.min.css") }}" rel="stylesheet" type="text/css" />
        <link href="{{ asset("assets/global/plugins/select2/css/select2-bootstrap.min.css") }}" rel="stylesheet" type="text/css" />

        {{-- File Input --}}
        <link href="{{ asset("assets/global/plugins/bootstrap-fileinput/bootstrap-fileinput.css") }}" rel="stylesheet" type="text/css" />
@endsection

@section('breadcumb')
	<li>
        <a href="{{ route('contatos.index') }}" class="nav-link nav-toggle">
            <span class="title">Contatos</span>
        </a>
        <i class="fa fa-circle"></i>
    </li>
    <li>
        Administrar telefones
    </li>
@endsection

@section('content')
	
    <h1 class="page-title">
    	Contatos
        <small>Administrar telefones</small>
    </h1>

    <a class="btn blue-sharp btn-outline sbold pull-right" data-toggle="modal" href="#telefone"><i class="fa fa-phone"></i> Novo Telefone</a>
    <div style="margin:0; padding:0; height:50px;">&nbsp;</div>

    <div class="portlet light bordered">
        <div class="portlet-title">
            <div class="caption font-dark">
                <i class="icon-settings font-dark"></i>
                <span class="caption-subject bold uppercase">{{$contato->name}}</b></span>
            </div>
            <div class="tools"> </div>
        </div>
        <div class="portlet-body">
            <table class="table table-striped table-bordered table-hover" id="sample_1">
                <thead>
                    <tr>
                        <th>Numero</th>
                        <th>Deletar</th>
                    </tr>
                </thead>
            <tbody>
                @foreach($contato->telefones as $r)
                    <tr>
                        <td>{{$r->numero}}</td>
                        <td>
                            <form role="form" action="{{ route('telefones.destroy', $r->id) }}" METHOD="POST">
                                {{ csrf_field() }}
                                {{ method_field('DELETE') }}<button type="submit">Deletar</button>
                            </form>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    </div>
                                

    {{-- Modal Adicionar Telefone --}}
    <div id="telefone" class="modal fade" tabindex="-1" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                    <h4 class="modal-title">Adicionar Telefone</h4>
                </div>
                <form role="form" action="{{ route('telefones.store') }}" id="telefone-form" METHOD="POST">
                    <input type="hidden" name="contato_id" value="{{$contato->id}}">
                <div class="modal-body">
                    <div class="scroller" style="height:150px" data-always-visible="1" data-rail-visible1="1">
                        {{ csrf_field() }}
                        <div class="form-body">
                            <div class="form-group">
                                <label>Número<span class="required"> * </span></label>
                                <input type="text" class="form-control" name="numero" placeholder="Enter número">
                            </div>
                        </div> 
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn dark btn-outline" data-dismiss="modal">Cancelar</button>
                    <button type="submit" class="btn blue-sharp">Adicionar</button>
                </div>
                </form>
            </div>
        </div>
    </div>
    
@endsection

@section('before-plugins')
        {{-- Select --}}
        <script src="{{ asset("assets/global/plugins/select2/js/select2.full.min.js") }}" type="text/javascript"></script>

        {{-- Input File --}}
        <script src="{{ asset("assets/global/plugins/bootstrap-fileinput/bootstrap-fileinput.js") }}" type="text/javascript"></script>

        {{-- Mask --}}
        <script src="{{ asset("assets/global/plugins/jquery-inputmask/jquery.inputmask.bundle.min.js") }}" type="text/javascript"></script>
        <script src="{{ asset("assets/global/plugins/jquery.input-ip-address-control-1.0.min.js") }}" type="text/javascript"></script>

        {{-- Validation --}}
        <script src="{{ asset("assets/global/plugins/jquery-validation/js/jquery.validate.js") }}" type="text/javascript"></script>
        <script src="{{ asset("assets/global/plugins/jquery-validation/js/additional-methods.js") }}" type="text/javascript"></script>
@endsection

@section('after-plugins')
        {{-- Select --}}
        <script src="{{ asset("assets/pages/scripts/components-select2.min.js") }}" type="text/javascript"></script>

        {{-- Mask --}}
        <script src="{{ asset("assets/pages/scripts/form-input-mask.min.js") }}" type="text/javascript"></script>

        {{-- Validation --}}
        <script src="{{ asset("assets/pages/scripts/form-validation.js") }}" type="text/javascript"></script>
@endsection

@section('script')
    <script type="text/javascript">
        
    </script>
@endsection

resources/views/home.blade.php
@extends('layouts.default')

@section('css-plugins')
@endsection

@section('breadcumb')
	<li>
		Index
	</li>
@endsection

@section('content')
	
    <h1 class="page-title">
    	CRM
        <small>Home</small>
    </h1>
    
@endsection

@section('before-plugins')
@endsection

@section('after-plugins')
@endsection

@section('scripts')

@endsection

resources/views/pages/home.blade.php
@extends('layouts.default')

@section('css-plugins')

@endsection

@section('breadcumb')
  <li>
            Home
  </li>
@endsection

@section('content')
    Bem vindo a Home!
@endsection

@section('before-plugins')
         
@endsection

@section('after-plugins')

@endsection

@section('script')

@endsection

resources/views/partials/menu.blade.php
<ul class="page-sidebar-menu  page-header-fixed " data-keep-expanded="false" data-auto-scroll="true" data-slide-speed="200" style="padding-top: 20px">
    <!-- DOC: To remove the sidebar toggler from the sidebar you just need to completely remove the below "sidebar-toggler-wrapper" LI element -->
    <!-- BEGIN SIDEBAR TOGGLER BUTTON -->
    <li class="sidebar-toggler-wrapper hide">
        <div class="sidebar-toggler">
            <span></span>
        </div>
    </li>
    <!-- END SIDEBAR TOGGLER BUTTON -->
    <li class="nav-item start" >
        <a href="{{ route('home') }}" class="nav-link nav-toggle">
            <i class="icon-home"></i>
            <span class="title">Home</span>
            <span class=""></span>
        </a>
    </li>
    <li class="heading">
        <h3 class="uppercase">Cadastros</h3>
    </li>
    <li class="nav-item {{strpos(Route::getFacadeRoot()->current()->uri(), 'ticket') !== false ? "active open" : ""}}">
        <a href="{{ route('contatos.index') }}" class="nav-link nav-toggle">
            <i class="fa fa-users"></i>
            <span class="title">Contatos</span>
            <span class="{{strpos(Route::getFacadeRoot()->current()->uri(), 'ticket') !== false ? "selected" : ""}}"></span>
        </a>
    </li>
</ul>